# ===========================================
# REDIS MODULE - CONFIGURATION GENERATION
# ===========================================

# Generate Redis configuration file
resource "local_file" "redis_config" {
  content = <<-EOT
# Redis Configuration for Cache Aside Pattern
# Generated by Terraform

# Basic Redis settings
port ${var.redis_port}
bind 0.0.0.0
protected-mode yes
requirepass ${var.redis_password}

# Cache Aside Pattern Configuration
maxmemory 256mb
maxmemory-policy allkeys-lru

# Persistence settings
save 900 1
save 300 10
save 60 10000

# Logging
loglevel notice
logfile /var/log/redis/redis.log

# Cache TTL Settings (for application use)
# Default TTL: ${var.cache_ttl_default}s
# Todo Data TTL: ${var.cache_ttl_todo_data}s  
# User Data TTL: ${var.cache_ttl_user_data}s
EOT
  
  filename = "${path.module}/redis.conf"
}

# Generate Docker Compose configuration for Redis
resource "local_file" "redis_docker_compose" {
  content = <<-EOT
version: '3.8'

services:
  redis:
    image: redis:${var.redis_version}
    container_name: ${var.project_name}-redis-${var.environment}
    ports:
      - "${var.redis_port}:6379"
    environment:
      - REDIS_PASSWORD=${var.redis_password}
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - ${var.project_name}-${var.environment}-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 10s

volumes:
  redis_data:
    name: ${var.project_name}-redis-${var.environment}-data

networks:
  ${var.project_name}-${var.environment}-network:
    external: true
EOT
  
  filename = "${path.module}/redis-docker-compose.yml"
}